name: salah_app
description: This is an Islamic Prayer App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  audioplayers: ^5.2.1
  bloc: ^8.1.2
  dio: ^5.3.4
  envied: ^0.5.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter


  flutter_bloc: ^8.1.3
  geolocator: ^11.0.0
  google_fonts: ^4.0.0
  hydrated_bloc: ^9.0.0
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  logger: ^2.0.2+1
  path_provider: ^2.1.2
  rxdart: ^0.27.7
  salah_repository:
    path: packages/salah_repository

dev_dependencies:
  bloc_test: ^9.1.2
  build_runner: ^2.4.8
  envied_generator: ^0.5.3
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  isar_generator: ^3.1.0+1
  mocktail: ^1.0.2
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/athans/
#  generate: true