name: open_salah_api
description: A Dart API Client for the Open-Salah API.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  flutter_lints: ^3.0.1
  http: ^1.1.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  logger: ^2.0.2+1
  geolocator: ^11.0.0
  envied: ^0.5.3
  isar: any
  isar_generator: any
  isar_flutter_libs: any
  path_provider: ^2.0.15
dev_dependencies:
  build_runner: ^2.4.8
  envied_generator: ^0.5.3
  mocktail: ^0.3.0
  test: ^1.24.9