name: salah_repository
description: A Dart Repository which manages the salah domain.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.6.0
  flutter_lints: ^3.0.1
  logger: ^2.0.2+1
  open_salah_api:
    path: ../open_salah_api
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  geolocator: ^11.0.0
  intl: any

dev_dependencies:
  build_runner: ^2.4.7
  coverage: ^1.0.3
  isar_generator: ^3.1.0+1
  json_serializable: ^6.3.1
  mocktail: ^1.0.0
  test: ^1.16.4
  analyzer: any
